### ISSUE TITLE
Error reading values after eot in gulp task

### ISSUE THREAD

**Issue by NickTomlin** [lacroixdesign/node-neat#12]
I get the following error when running my gulp task:

```shell 
/node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets
/stylesheets/helpers/font-source-declaration:22: error: error reading values after eot
```

My gulp config: 

```javascript
  return gulp.src('./my/app.scss')
    .pipe(sass({
      includePaths: require('node-neat').includePaths,
    }))
```

This seems to be due to the recent changes in node bourbon? Rolling back to `node-neat@1.4.2` resolves the issue. I've experienced it on Debian and Yosemite.

**Comment by NickTomlin** [comment]
This seemed to be due to an outdated libsass binary pulled in by node-gulp. Closing.

**Comment by iamlacroix** [comment]
This issue somehow slipped through, sorry about that! Glad you were able to figure it out.

**Comment by furley** [comment]
I'm having a similar issue. Could you explain a bit more about how you were able to resolve this?

**Comment by cjmaio** [comment]
@NickTomlin how were you able to resolve the issue? I'm encountering a similar issue, and have updated Gulp.

**Comment by NickTomlin** [comment]
@cjmaio rolling back to node-neat `1.4.2` did the trick for me. Did you clear out your `node_modules` directory and reinstall?

**Comment by cjmaio** [comment]
@NickTomlin I had to just include a different version of sass from Node and it worked. Thanks, though!

**Comment by iamjonas** [comment]
Rolling back to node-neat@1.4.2 didn't work at all for me tho, any suggestions?
