### ISSUE TITLE
Using with Webpack?

### ISSUE THREAD

**Issue by kjs3** [lacroixdesign/node-neat#13]
This is a question not an issue but has anyone used this with webpack?
I've been fiddling around with a webpack config for awhile and can't get @import "neat" or @import "~neat" statements to work.

**Comment by iamlacroix** [comment]
The following is a sample from a working webpack config that I began experimenting with recently. I've been looking to switch to webpack myself, but haven't had time to fully configure/explore it, let alone use it in a client/production project.

I am outputting to a separate CSS file, but embedded styles would work too. Let me know if this helps!

```javascript
var ExtractTextPlugin = require("extract-text-webpack-plugin");

/*
 * node-neat's `includePaths` property returns an array with the paths to
 * both Neat and Bourbon. The `sassPaths` variable will equal something
 * like this:
 *
 *   includePaths[]=/path/to/node-bourbon&includePaths[]=/path/to/node-neat
 *
 * We will later use this variable in our Sass loader's query params. See:
 *
 *   https://github.com/jtangelder/sass-loader#sass-options
 *
 */
var sassPaths = require("node-neat").includePaths.map(function(sassPath) {
  return "includePaths[]=" + sassPath;
}).join("&");

module.exports = {
  // Naturally, this is just a tiny excerpt of the full config
  // ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        // Here we append our `sassPath` variable as the query parameters:
        loader: ExtractTextPlugin.extract("style", "css!sass?" + sassPaths)
      },
    ]
  },
  plugins: [
    new ExtractTextPlugin("[name].css"),
  ]
};
```

**Comment by kjs3** [comment]
Could you maybe try this on IO.js 1.2? I don't know what part of my stack is borking on this.

**Comment by kjs3** [comment]
I changed my webpack config based on what you had and started actually getting compile errors which was great. Then I had to add both @import 'bourbon'; and @import 'neat'; to get it to compile. It seems to be ok now though.

**Comment by iamlacroix** [comment]
I began looking into it further per your reply, and noticed that the sass-loader was [updated to 1.0.0](https://github.com/jtangelder/sass-loader/releases/tag/v1.0.0) a couple days ago, which I was not yet using in my setup. After updating, it would no longer find my local imports which were relative to the Sass file importing them:

```scss
// assets/css/main.scss

// Importing `assets/css/settings/_typography.scss` results in:
//
//   File to import not found or unreadable: ./settings/typography.scss
//
@import 'settings/typography';
```

Updating my `sassPaths` variable to the following fixed it (NOTE: it's path-specific to my project), however I don't know the source of this change yet. Not sure if you'll encounter that issue too, but wanted to post it just in case.

```javascript
var sassPaths = require('node-neat').with([
  // Adding the path to my Sass files relative to webpack.config.js
  path.resolve(__dirname, "./assets/css")
]).map(function(sassPath) {
  return "includePaths[]=" + sassPath;
}).join("&");
```

**Comment by kjs3** [comment]
Yeah, that fixes path resolving for me. So mine is…

```
// Note: I changed some var/arg names.
var sassNeatPaths = require("node-neat").with([
    path.resolve(__dirname, "./app/assets/styles")
  ]).map(function(neatPath) {
    return "includePaths[]=" + neatPath;
}).join("&");
```

**Comment by kjs3** [comment]
Also, the loader config is super picky or maybe I don't understand the difference between the following.

This works and is my current config for scss files:

```
{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css?sourceMap!sass?sourceMap&' + sassNeatPaths, 'autoprefixer') }
```

But separating the css and sass loaders does NOT work:

```
// build fails
{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css?sourceMap', 'sass?sourceMap&' + sassNeatPaths, 'autoprefixer') }
```

Also, the style loader MUST be separate so this fails:

```
// build fails
{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style!css?sourceMap!sass?sourceMap&' + sassNeatPaths, 'autoprefixer') }
```

If anyone understands the nuance here I'd love to know.

**Comment by iamlacroix** [comment]
The API for `ExtractTextPlugin.extract` is:

```javascript
ExtractTextPlugin.extract([notExtractLoader], loader, [options])
```

So it appears the `style` loader will be used for instances when it's not being extracted to a file (to write it to the DOM), and `'css?sourceMap!sass?sourceMap&' + sassNeatPaths` loaders are used when extracting.

Not sure why the autoprefixer would be working in the first example; it's being passed in as the options object. Is it actually prefixing? It might need to be changed to something like the following (I've also swapped the order of the autoprefixer and Sass loaders so that it prefixes after compiling Sass).

```javascript
ExtractTextPlugin.extract('style', 'css?sourceMap!autoprefixer!sass?sourceMap&' + sassNeatPaths)
```

[https://github.com/webpack/extract-text-webpack-plugin#api](https://github.com/webpack/extract-text-webpack-plugin#api)

**Comment by kjs3** [comment]
Ok, I get it now. Thanks. 
Autoprefixer wasn't actually working but it is now. Here's my loader:

```
{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css?sourceMap!sass?sourceMap&' + sassNeatPaths + '!autoprefixer') }
```

**Comment by iamlacroix** [comment]
Glad it's working!

One thing to note is that loaders are processed from right to left, so autoprefixer is running before your Sass is compiled. It might be better to swap the order so it runs on the compiled CSS instead. Something like:

```javascript
{ test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css?sourceMap!autoprefixer!sass?sourceMap&' + sassNeatPaths) }
```

See: [http://webpack.github.io/docs/using-loaders.html#loaders-in-require](http://webpack.github.io/docs/using-loaders.html#loaders-in-require)

**Comment by kjs3** [comment]
Good call. Changed.

**Comment by chaseadamsio** [comment]
Thanks for this guys, probably saved me hours of banging my head against the wall trying to get it running properly.

**Comment by droplab** [comment]
Yes, thank you -- I was struggling with this for several hours.

**Comment by ryandeussing** [comment]
In case it saves someone else a couple hours: my working imports look like this:

```html
@import "~bourbon";
@import "~bourbon-neat";
```
