### ISSUE TITLE
Node-neat setup with LibSass and gulp

### ISSUE THREAD

**Issue by ju73** [lacroixdesign/node-neat#17]
Hello!
I'm trying to setup node-neat to work with gulp.
I'm new to terminal, LibSass, npm, ruby and all, so I'm probably missing something pretty easy..

Here is my config :
package.json
```json
{
  "name": "jlo_resp_vad",
  "version": "1.0.0",
  "scripts": {
    "sass:dev": "./node_modules/.bin/gulp",
    "sass:prod": "./node_modules/.bin/gulp sass:prod"
  },
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-sass": "^2.0.4",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-watch": "^4.3.3",
    "node-neat": "^1.7.2",
    "bourbon-libsass": "^1.0.0",
    "gulp-livereload": "^3.8.0",
    "mappy-breakpoints": "^0.2.1"
  }
}
```

gulpfile.js
```javascript
'use strict';

var gulp = require('gulp');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');
var autoprefixer = require('gulp-autoprefixer');
var livereload = require('gulp-livereload');
var neat = require('node-neat');

gulp.task('sass:prod', function () {
  gulp.src('./sass/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(autoprefixer({
       browsers: ['last 2 version']
    }))
    .pipe(gulp.dest('./css'));
});

gulp.task('sass:dev', function () {
  gulp.src('./sass/*.scss')
    .pipe(sourcemaps.init())
    .pipe(sass({
	  includePaths: require('node-neat').includePaths
	}).on('error', sass.logError))
    .pipe(autoprefixer({
      browsers: ['last 2 version']
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./css'))
	.pipe(livereload())
});

gulp.task('sass:watch', function () {
  livereload.listen(35729);
  gulp.watch('./sass/**/*.scss', ['sass:dev']);
});

gulp.task('default', ['sass:dev', 'sass:watch']);
```

import in css :
```scss
@import "node_modules/node-neat/node_modules/bourbon-neat/bin/neat";
```

When trying to run gulp, I get this error :
```shell
node_modules/node-neat/node_modules/bourbon-neat/bin/neat
1:1  invalid top-level expression
```

Maybe the functions I'm calling to are not complete...
but when opening the neat file, I see this on the first line :
```
#!/usr/bin/env ruby
```
problem I see is I'm using LibSass and not ruby...

Trying to troubleshoot but it takes some time to just understand the way all this works, not there yet..
Thanks in advance for any help!!

**Comment by iamlacroix** [comment]
Hi!

Everything looks good except for the SCSS import, [change it to](https://github.com/lacroixdesign/node-neat#stylesheet-usage):

```scss
@import "bourbon";
@import "neat";
```

Additionally, you can remove the `bourbon-libsass` package from your `package.json`, as it is not being used.

**Comment by ju73** [comment]
Hi!
Thanks a lot, my test declarations work indeed!! :+1: 

Just another quick question if you have time : 
So scss finds the files all by itself with libsass, you don't need to declare the paths? Same thing for the partial scss?
@import "variables/_couleurs.scss"; 
should be only :
@import "_couleurs.scss";

**Comment by iamlacroix** [comment]
You can omit the leading underscore and the file extension, e.g.

```scss
// Use:
@import "variables/couleurs"; 
// Instead of:
@import "variables/_couleurs.scss"; 
```

You will still need the rest of the path, unless you are including additional load paths explicitly with the `includePaths` property in your Sass config. In the case of node-neat, this is exactly what is happening and is the reason you only need a simple `@import "neat"` in your SCSS file.

**Comment by ju73** [comment]
Thank you very much for the quick answers and for node-neat!!
Starting to get the gist of it
Cheers
Julie
