### ISSUE TITLE
Issues building styles with Bourbon, Neat, Sass loader

### ISSUE THREAD

**Issue by kingscott** [lacroixdesign/node-neat#21]
Hey all, running into some issues that have me a bit stumped. I have a small JS library that when compiled, exports a [compiled] minified JS file and a css file (compiled from sass). 

My webpack config looks like this:

```javascript
const path = require('path');
const bourbon = require('node-bourbon').includePaths;
const neat = require('node-neat').includePaths;
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: [
    './some/js/file.js',
    './styles/folder/styles.scss'
  ],
  output: {
    path: path.join(__dirname, '/dist/output'),
    filename: 'file.js',
    publicPath: '/'
  },
  plugins: [
    // Some plugins
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    }),
    new ExtractTextPlugin('styles.css')
  ],
  module: {
    preLoaders: [
      { test: /\.json$/, exclude: /node_modules/, loader: 'json' }
    ],
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        presets: ['es2015']
      },
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap!sass?sourceMap?outputStyle=compressed&includePaths[]=' + encodeURIComponent(bourbon) + '&includePaths[]=' + encodeURIComponent(neat[1]))
      }
    ]
  },
}
```

The above is being run with `NODE_ENV=production webpack -p --config webpack.production.config.js`. Seems pretty normal. 

But I'm getting an error: `Module build failed: BrowserslistError: Unknown version 55 of and_chr`. Been working on it for a few hours, but unable to make any new progress. Any idea what this error means and what the deal with it is? Thanks for any help!

Info:
*Node* version -> 6.2.2
*Webpack* version -> 1.14.0
*ExtractTextPlugin* -> 1.0.1
*OS* -> MacOS Sierra
*Language* -> JavaScript

**Comment by kingscott** [comment]
Solved this. Sorry!

**Comment by iamlacroix** [comment]
Oops, going through some old GH notifications and just now saw this. Glad you figured it out!
